name: Build release

on: 
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  windows-release:
    name: create Windows release
    runs-on: windows-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: build artifacts
      run: |
        python -m pip install pyinstaller
        python -m pip install -r "./requirements.txt"
        python -OO -m PyInstaller -F -n "YGOtoTTS-$GITHUB_REF-win32" "./YGOtoTTS/__main__.py"
      shell: cmd
      id: build
    - name: create release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        draft: false
        prerelease: false
        release_name: YGOtoTTS ${{ github.ref }}
        tag_name: ${{ github.ref }}
    - name: upload artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url}}
        asset_path: .\dist\YGOtoTTS-${{ github.ref }}-win32.exe
        asset_name: YGOtoTTS-${{ github.ref }}-win32.exe
        asset_content_type: application/x-ms-dos-executable
   
